service: sls-meetup-alexa-skill

provider:
  name: aws
  runtime: nodejs12.x
custom:
  alexa:
    vendorId: ${env:VENDOR_ID}
    clientId: ${env:CLIENT_ID}
    clientSecret: ${env:CLIENT_SECRET}
    localServerPort: ${env:LOCAL_SERVER_PORT}
    skills:
      - id: ${env:SKILL_ID}
        manifest:
          publishingInformation:
            locales:
              it-IT:
                name: MeetupEvents
          apis:
            custom:
              endpoint:
                uri: ${env:ENDPOINT_URI}
          manifestVersion: '1.0'
        models:
          it-IT:
            interactionModel:
              languageModel:
                invocationName: meetup events
                intents:
                  - name: MeetupIntent
                    samples:
                      - 'i miei eventi'
                      - 'i miei meetup'
                      - 'qualche meetup interessante'
                      - 'meetup'
                  - name: AMAZON.HelpIntent
                    samples: []
                  - name: AMAZON.CancelIntent
                    samples: []
                  - name: AMAZON.StopIntent
                    samples: []

functions:
  hello:
    handler: dist/handler.meetupHandler
    events:
      - alexaSkill: ${env:ALEXA_SKILL}

plugins:
  - serverless-alexa-skills
  - serverless-dotenv-plugin
