service: sls-meetup-alexa-skill

provider:
  name: aws
  runtime: nodejs12.x
custom:
  alexa:
    vendorId: ${env:VENDOR_ID}
    clientId: ${env:CLIENT_ID}
    clientSecret: ${env:CLIENT_SECRET}
    localServerPort: ${env:LOCAL_SERVER_PORT}
    skills:
      - id: ${env:SKILL_ID}
        manifest:
          publishingInformation:
            locales:
              it-IT:
                name: MeetupEvents
          apis:
            custom:
              endpoint:
                uri: ${env:ENDPOINT_URI}
          manifestVersion: '1.0'
        models:
          it-IT:
            interactionModel:
              languageModel:
                invocationName: meetup events
                intents:
                  - name: MeetupIntent
                    samples:
                      - 'i miei eventi'
                      - 'i miei meetup'
                      - 'qualche meetup interessante'
                      - 'meetup'
                  - name: AMAZON.HelpIntent
                    samples: []
                  - name: AMAZON.CancelIntent
                    samples: []
                  - name: AMAZON.StopIntent
                    samples: []

functions:
  hello:
    handler: dist/handler.meetupHandler
    events:
      - alexaSkill: ${env:ALEXA_SKILL}

#      - alexaSmartHome: amzn1.ask.skill.xx-xx-xx-xx
#      - iot:
#          sql: "SELECT * FROM 'some_topic'"
#      - cloudwatchEvent:
#          event:
#            source:
#              - "aws.ec2"
#            detail-type:
#              - "EC2 Instance State-change Notification"
#            detail:
#              state:
#                - pending
#      - cloudwatchLog: '/aws/lambda/hello'
#      - cognitoUserPool:
#          pool: MyUserPool
#          trigger: PreSignUp
#      - alb:
#          listenerArn: arn:aws:elasticloadbalancing:us-east-1:XXXXXX:listener/app/my-load-balancer/50dc6c495c0c9188/
#          priority: 1
#          conditions:
#            host: example.com
#            path: /hello


plugins:
  - serverless-alexa-skills
  - serverless-dotenv-plugin
